version: '3'

services:
    prometheus:
        image: ubuntu/prometheus:edge
        ports:
            - 9090:9090
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./config/alerts.yml:/etc/prometheus/alerts.yml
        networks:
            - lmatest

    node-exporter:
        image: prom/node-exporter
        ports:
            - 9100:9100
        networks:
            - lmatest

    telegraf:
        image: ubuntu/telegraf:edge
        ports:
            - 9273:9273
        volumes:
            - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
        networks:
            - lmatest

    alertmanager:
        image: ubuntu/prometheus-alertmanager:edge
        ports:
            - 9093:9093
        volumes:
            - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        networks:
            - lmatest

    grafana:
        image: ubuntu/grafana:edge
        ports:
            - 3000:3000
        volumes:
            - ./config/grafana/provisioning/:/etc/grafana/provisioning/
        networks:
            - lmatest

    cortex:
        image: ubuntu/cortex:edge
        ports:
            - 9009:9009
        networks:
            - lmatest

    tests:
        image: localtest/lma-integration-tests
        ports:
            - 5001:5001
            - 8080:8080
        networks:
            - lmatest

networks:
    lmatest:
        driver: bridge
